#spring:
#  application:
#    name: payment
#    datasource:
#      driver-class-name: com.mysql.jdbc.Drive
#      url: jdbc:mysql://localhost:3306/neoflex_task?&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC
#      username: root
#      password: 123456
#server:
#  port: 9080
#
